server:
  port: ${PORT:8080}
fondo:
  security:
    use-redis: false
    single-deviceLogin: true
    token-expireTime: 30
    sign-key: ^%$gf75H5g2g4bnH$#^fd3r6$e^$
    store-permissions: true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL:jdbc:mysql://192.168.50.127:3306/fondo_security?characterEncoding=utf-8}
    username: root
    password: root
  redis:
    host: ${REDIS_HOST:192.168.50.127}
    port: ${REDIS_PORT:6379}
    timeout: 5000 #连接超时 毫秒
    jedis:
      pool:
        maxActive: 3
        maxIdle: 3
        minIdle: 1
        maxWait: -1 #连接池最大等行时间 -1没有限制
logging:
  level:
    com.oktfolio.fondo.dao: DEBUG
    org.springframework.security: DEBUG
mapper:
  mappers:
    - tk.mybatis.mapper.common.Mapper
  notEmpty: true
  style: camelhump